import '../styles/globals.css'
export { default as Icon } from './components/Icon'
export { default as IconNames } from './components/Icon/type'
export { default as Button } from './components/Button'
export { default as Space } from './components/Space'
